In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns 
from scipy import stats
sns.set()
german_data = pd.read_csv("C:\Project_Files\Capstone1_Files\German_CreditRating_Cleaned_Data.csv")

In [85]:
german_data.columns

Index(['Unnamed: 0', 'checking_account_status', 'duration', 'credit_history',
       'purpose', 'credit_amount', 'savings_account', 'present_employment',
       'installment_rate', 'personal_status_sex', 'debtors_guarontors',
       'present_residence', 'property', 'age', 'installment_plans', 'housing',
       'credits_at_bank', 'job', 'people_liable', 'telephone', 'worker',
       'credibility'],
      dtype='object')

In [121]:
# function to filter persons with good and bad credit
def good_bad_credit_data(col1,col2='credibility'):
    good_credit_data = pd.DataFrame(german_data[col1][german_data[col2]== 1])
    bad_credit_data = pd.DataFrame(german_data[col1][german_data[col2]== 0])
    return (good_credit_data,bad_credit_data)

# function to calculate the observed values for each attribute columns
def observed_values(df1,df2,col1,col2):
    df1[col2]=1
    df2[col2]=1                  
    good_count = df1.groupby(col1).sum()
    bad_count =  df2.groupby(col1).sum()
    observed_counts = np.array([good_count.iloc[:,0],bad_count.iloc[:,0]])
    return (observed_counts)

# function to calculate the Expected counts for each attribute columns
def Expected_values(observed_count):
    expected_product= np.empty(shape=observed_count.shape)
    overall_total = 0
    for i in range(observed_count.shape[0]):
        overall_total = overall_total + np.sum(observed_count[i])
        for j in range(observed_count.shape[1]):
            expected_product[i][j] = (np.sum(observed_count[i])*np.sum(observed_count[:,j]))
    return (expected_product/overall_total)

In [132]:
#Attribute 1: (qualitative) 
#Status of existing checking account 

good_attr1,bad_attr1 = good_bad_credit_data('checking_account_status')
attr1_observed_counts = observed_values(good_attr1,bad_attr1,'checking_account_status','checking_account_status_counts')
print(attr1_observed_counts)
attr1_expected_counts = Expected_values(attr1_observed_counts)
print(attr1_expected_counts)

stats.chisquare(f_obs= attr1_observed_counts,f_exp= attr1_expected_counts,axis= None) 


[[139 164  49 348]
 [135 105  14  46]]
[[ 191.8  188.3   44.1  275.8]
 [  82.2   80.7   18.9  118.2]]


Power_divergenceResult(statistic=123.72094351626561, pvalue=1.2850305728305954e-23)

In [131]:
stats.chi2_contingency(observed=attr1_observed_counts)

(123.72094351626561,
 1.2189020722893755e-26,
 3,
 array([[ 191.8,  188.3,   44.1,  275.8],
        [  82.2,   80.7,   18.9,  118.2]]))

* Null hypothesis is to prove that the two categorical variables Good and Bad creditors are independent of status of checking account but the p value is very low, there by we can reject the Null hypothesis. This clearly indicates  that the two categories are dependent on the Status of checking Account.

In [137]:
#Attribute 2: (numerical) 
#Duration in month 



In [138]:
#Attribute 3: (qualitative) 
#Credit history 

good_attr3,bad_attr3 = good_bad_credit_data('credit_history')
attr3_observed_counts = observed_values(good_attr3,bad_attr3,'credit_history','credit_history_counts')
print(attr3_observed_counts)
stats.chi2_contingency(observed=attr3_observed_counts)

[[ 15  21 361  60 243]
 [ 25  28 169  28  50]]


(61.691396964595498,
 1.2791872956751013e-12,
 4,
 array([[  28. ,   34.3,  371. ,   61.6,  205.1],
        [  12. ,   14.7,  159. ,   26.4,   87.9]]))

* Null hypothesis can be rejected as the p value is very low, there by there is a dependency of the two variables on Credit History

In [139]:
#Attribute 4: (qualitative) 
#Purpose 

good_attr4,bad_attr4 = good_bad_credit_data('purpose')
attr4_observed_counts = observed_values(good_attr4,bad_attr4,'purpose','purpose_counts')
print(attr4_observed_counts)
stats.chi2_contingency(observed=attr4_observed_counts)

[[152  86 123 218   8  14  28   8  63]
 [ 94  17  58  62   4   8  22   1  34]]


(33.284725448233324,
 5.4721150411461247e-05,
 8,
 array([[ 172.2,   72.1,  126.7,  196. ,    8.4,   15.4,   35. ,    6.3,
           67.9],
        [  73.8,   30.9,   54.3,   84. ,    3.6,    6.6,   15. ,    2.7,
           29.1]]))

* Null hypothesis can be rejected as the p value is very low, there by there is a dependency of the two variables on Purpose.

In [ ]:
#Attribute 5: (numerical) 
#Credit amount

In [140]:
#Attibute 6: (qualitative) 
#Savings account/bonds 

good_attr6,bad_attr6 = good_bad_credit_data('savings_account')
attr6_observed_counts = observed_values(good_attr6,bad_attr6,'savings_account','savings_account_counts')
print(attr6_observed_counts)
stats.chi2_contingency(observed=attr6_observed_counts)

[[386  69  52  42 151]
 [217  34  11   6  32]]


(36.098928192418697,
 2.7612142385682596e-07,
 4,
 array([[ 422.1,   72.1,   44.1,   33.6,  128.1],
        [ 180.9,   30.9,   18.9,   14.4,   54.9]]))

* Null hypothesis can be rejected as the p value is very low, there by there is a dependency of the two variables on Savings account/bonds

In [142]:
#Attribute 7: (qualitative) 
#Present employment since 

good_attr7,bad_attr7 = good_bad_credit_data('present_employment')
attr7_observed_counts = observed_values(good_attr7,bad_attr7,'present_employment','present_employment_counts')
print(attr7_observed_counts)
stats.chi2_contingency(observed=attr7_observed_counts)

[[ 39 102 235 135 189]
 [ 23  70 104  39  64]]


(18.368273846696798,
 0.0010454523491402539,
 4,
 array([[  43.4,  120.4,  237.3,  121.8,  177.1],
        [  18.6,   51.6,  101.7,   52.2,   75.9]]))

* Null hypothesis can be rejected as the p is comparitively higher than other attributes but not significant enough, there by there is a dependency of the two variables on Savings account/bonds

In [143]:
#Attribute 8: (numerical) 
#Installment rate in percentage of disposable income

good_attr8,bad_attr8 = good_bad_credit_data('installment_rate')
attr8_observed_counts = observed_values(good_attr8,bad_attr8,'installment_rate','installment_rate_counts')
print(attr8_observed_counts)
stats.chi2_contingency(observed=attr8_observed_counts)


[[102 169 112 317]
 [ 34  62  45 159]]


(5.4767921451537527,
 0.14003331221284809,
 3,
 array([[  95.2,  161.7,  109.9,  333.2],
        [  40.8,   69.3,   47.1,  142.8]]))

* Null hypothesis cannot be rejected as the p value is significance enough, there by we can conclude that the two variables are independent of Installment Rate.

In [144]:
#Attribute 9: (qualitative) 
#Personal status and sex

good_attr9,bad_attr9 = good_bad_credit_data('personal_status_sex')
attr9_observed_counts = observed_values(good_attr9,bad_attr9,'personal_status_sex','personal_status_sex_counts')
print(attr9_observed_counts)
stats.chi2_contingency(observed=attr9_observed_counts)

[[ 30 201 402  67]
 [ 20 109 146  25]]


(9.6052139593360497,
 0.022238005469268771,
 3,
 array([[  35. ,  217. ,  383.6,   64.4],
        [  15. ,   93. ,  164.4,   27.6]]))

* Null hypothesis can be rejected as the p value is comparitively higher than other attributes but not more than the significance level of .05, there by there is a dependency of the two variables on Personal status and sex

In [146]:
#Attribute 10: (qualitative) 
#Other debtors / guarantors 

good_attr10,bad_attr10 = good_bad_credit_data('debtors_guarontors')
attr10_observed_counts = observed_values(good_attr10,bad_attr10,'debtors_guarontors','debtors_guarontors_counts')
print(attr10_observed_counts)
stats.chi2_contingency(observed=attr10_observed_counts)


[[635  23  42]
 [272  18  10]]


(6.645366537264243, 0.036055954027247226, 2, array([[ 634.9,   28.7,   36.4],
        [ 272.1,   12.3,   15.6]]))

* Null hypothesis can be rejected as the p value is comparitively higher than other attributes but not more than the significance level of .05, there by there is a dependency of the two variables on Other debtors / guarantors

In [147]:
#Attribute 11: (numerical) 
#Present residence since 

good_attr11,bad_attr11 = good_bad_credit_data('present_residence')
attr11_observed_counts = observed_values(good_attr11,bad_attr11,'present_residence','present_residence_counts')
print(attr11_observed_counts)
stats.chi2_contingency(observed=attr11_observed_counts)


[[ 94 211 106 289]
 [ 36  97  43 124]]


(0.74929644838805132,
 0.86155213204131753,
 3,
 array([[  91. ,  215.6,  104.3,  289.1],
        [  39. ,   92.4,   44.7,  123.9]]))

* Null hypothesis cannot be rejected as the p value is significant enough, there by we can conclude that the two variables are independent of Present residence.

In [148]:
#Attribute 12: (qualitative) 
#Property 

good_attr12,bad_attr12 = good_bad_credit_data('property')
attr12_observed_counts = observed_values(good_attr12,bad_attr12,'property','property_counts')
print(attr12_observed_counts)
stats.chi2_contingency(observed=attr12_observed_counts)


[[222 161 230  87]
 [ 60  71 102  67]]


(23.719551283864707,
 2.8584415733250017e-05,
 3,
 array([[ 197.4,  162.4,  232.4,  107.8],
        [  84.6,   69.6,   99.6,   46.2]]))

* Null hypothesis can be rejected as the p value is below the significance level of 0.05 , there by we can conclude that the two variables are dependent on Property

In [150]:
#Attribute 13: (numerical) 
#Age in years 



In [151]:
#Attribute 14: (qualitative) 
#Other installment plans

good_attr14,bad_attr14 = good_bad_credit_data('installment_plans')
attr14_observed_counts = observed_values(good_attr14,bad_attr14,'installment_plans','installment_plans_counts')
print(attr14_observed_counts)
stats.chi2_contingency(observed=attr14_observed_counts)

[[ 82  28 590]
 [ 57  19 224]]


(12.839187735866137, 0.0016293178186473534, 2, array([[  97.3,   32.9,  569.8],
        [  41.7,   14.1,  244.2]]))

* Null hypothesis can be rejected as the p value is below the significance level of 0.05 , there by we can conclude that the two variables are dependent on Other installment plans

In [152]:
#Attribute 15: (qualitative) 
#Housing

good_attr15,bad_attr15 = good_bad_credit_data('housing')
attr15_observed_counts = observed_values(good_attr15,bad_attr15,'housing','housing_counts')
print(attr15_observed_counts)
stats.chi2_contingency(observed=attr15_observed_counts)


[[109 527  64]
 [ 70 186  44]]


(18.199841582563622,
 0.00011167465374597684,
 2,
 array([[ 125.3,  499.1,   75.6],
        [  53.7,  213.9,   32.4]]))

* Null hypothesis can be rejected as the p value is below the significance level of 0.05 , there by we can conclude that the two variables are dependent on Housing

In [ ]:
#Attribute 16: (numerical) 
#Number of existing credits at this bank 



In [153]:
#Attribute 17: (qualitative) 
#Job 
#A171 : unemployed/ unskilled - non-resident 
#A172 : unskilled - resident

good_attr17,bad_attr17 = good_bad_credit_data('job')
attr17_observed_counts = observed_values(good_attr17,bad_attr17,'job','job_counts')
print(attr17_observed_counts)
stats.chi2_contingency(observed=attr17_observed_counts)


[[ 15 144 444  97]
 [  7  56 186  51]]


(1.8851560280131707,
 0.59658159188434312,
 3,
 array([[  15.4,  140. ,  441. ,  103.6],
        [   6.6,   60. ,  189. ,   44.4]]))

* Null hypothesis cannot be rejected as the p value is significant enough, there by we can conclude that the two variables are independent of Job factor

In [ ]:
#Attribute 18: (numerical) 
#Number of people being liable to provide maintenance for

In [154]:
#Attribute 19: (qualitative) 
#Telephone 

good_attr19,bad_attr19 = good_bad_credit_data('telephone')
attr19_observed_counts = observed_values(good_attr19,bad_attr19,'telephone','telephone_counts')
print(attr19_observed_counts)
stats.chi2_contingency(observed=attr19_observed_counts)


[[409 291]
 [187 113]]


(1.1725585310208855, 0.27887615430357426, 1, array([[ 417.2,  282.8],
        [ 178.8,  121.2]]))

* Null hypothesis cannot be rejected as the p value is significant enough, there by we can conclude that the two variables are independent of Telephone

In [155]:
#Attribute 20: (qualitative) 
#foreign worker 

good_attr20,bad_attr20 = good_bad_credit_data('worker')
attr20_observed_counts = observed_values(good_attr20,bad_attr20,'worker','worker_counts')
print(attr20_observed_counts)
stats.chi2_contingency(observed=attr20_observed_counts)



[[667  33]
 [296   4]]


(5.8215759150338613, 0.015830754902852885, 1, array([[ 674.1,   25.9],
        [ 288.9,   11.1]]))

In [ ]:
* Null hypothesis can be rejected as the p value is below the significance level of 0.05 , there by we can conclude that the two variables are dependent on Foreign Worker